#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
source "$SCRIPT_DIR/lib/env.sh"

cron_minute=$(get_env "CRON_MINUTE" "0")
cron_hour=$(get_env "CRON_HOUR" "0")
cron_time=$(get_env "CRON_TIME" "$cron_minute $cron_hour * * *")
test_env=$(get_env "TEST_ENV" false)

echo "$cron_time backup >> /var/log/backup.log" > /etc/crontabs/root

echo "Launching cron service..."

if [ ! -f "/var/log/backup.log" ]; then
    touch /var/log/backup.log
fi

if [ "$test_env" = true ]; then
    timeout 1 run-cron-service
else
    run-cron-service
fi
